Added tests for frontend and backend, improved server
Dimundra/Form-builder-training-project pull request #3
Opened 2021-09-02 22:29 UTC by Dimundra

Done task https://jira.softserveinc.com/browse/PTP-18, https://jira.softserveinc.com/browse/PTP-17, https://jira.softserveinc.com/browse/PTP-20

2021-09-06 09:04 UTC, kibernetika requested changes

2021-09-06 09:04 UTC, kibernetika commented on server/package.json
> +    "nodemon": "^2.0.12",
For what you need nodemon? I think webpack can monitor file changes and do hot reload server or I'm wrong?

2021-09-06 09:04 UTC, kibernetika commented on server/server.js
> +  console.log('server has started on port 3002...');
For port use const and set it here and in server config.

2021-09-06 09:04 UTC, kibernetika commented on server/server.js
> +  console.log(err);
Maybe it change on console.error

2021-09-06 09:36 UTC, Dimundra commented on server/package.json
> +    "nodemon": "^2.0.12",
At this moment we haven't discussed anything about webpack on backend. To say you honestly I wasn't even aware about webpack's ability to handle backend. I will remove nodemon from the backend, because of your suggestion and at this moment personally I am not using it in the named commit.

2021-09-06 09:38 UTC, Dimundra commented on server/server.js
> +  console.log('server has started on port 3002...');
Will do that in the next named commit!

2021-09-06 10:21 UTC, Dimundra commented on server/package.json
> +    "nodemon": "^2.0.12",
Done!

2021-09-06 10:21 UTC, Dimundra commented on server/server.js
> +  console.log('server has started on port 3002...');
Done!

2021-09-06 10:21 UTC, Dimundra commented on server/server.js
> +  console.log(err);
Done!

2021-09-07 07:25 UTC, kibernetika approved these changes

2021-09-07 08:10 UTC, merged