Implemented basic JWT server side authentication
Dimundra/Form-builder-training-project pull request #6
Opened 2021-09-20 15:08 UTC by Dimundra

2021-09-21 07:00 UTC, kibernetika requested changes

2021-09-21 07:00 UTC, kibernetika commented on server/server.js
> +      method: 'GET',
Remove this route

2021-09-21 08:55 UTC, Dimundra commented on server/server.js
> +    {
No need for custom 404 error to my mind

2021-09-21 08:55 UTC, Dimundra commented on server/server.js
> +    {
I think it would be better to just erase this route

2021-09-21 11:11 UTC, Dimundra commented on server/server.js
> +        const decodedCredentials = Buffer.from(encodedCredentials, 'base64')
Removed such variables completely

2021-09-21 11:36 UTC, Dimundra commented on server/server.js
> +          const token = JWT.sign(payload, secret, { expiresIn: '30000ms' });
Done!

2021-09-22 10:29 UTC, kibernetika requested changes

2021-09-22 10:29 UTC, kibernetika commented on server/server.js
> +const users = [
Line 12-39 move to separate file in folder "services\tokenValidation.js", secret move to file const.js in server folder.

2021-09-22 10:29 UTC, kibernetika commented on server/server.js
> +        if (email === '' || password === '') {
Lines 63-79 move to separate service services\auth.js

2021-09-27 08:04 UTC, kibernetika requested changes

2021-09-27 08:04 UTC, kibernetika commented on server/server.js
> +  server.route([loginRoute]);
Create for routs joining separate file inside route folder. Inside this file connect all other routs' files and after that connect it here.

2021-09-27 08:04 UTC, kibernetika commented on server/services/tokenValidation.js
> +      isValid = true;
add 'return' here

2021-09-27 08:04 UTC, kibernetika commented on client/src/app/store/reducers/errorReducer.js
> +  validationError: {
doesn't create a separate section of the store for error types.

2021-09-27 10:37 UTC, Dimundra commented on client/src/app/store/actionCreators/authActions.js
> +function initializeAuthentication(email, password, redirect) {
Done!

2021-09-27 10:59 UTC, Dimundra commented on client/src/app/store/actionTypes.js
> +  CLEAR_ERRROS: 'CLEAR_ERRROS',
Done

2021-09-27 11:16 UTC, Dimundra commented on client/src/app/store/reducers/errorReducer.js
> +  validationError: {
Done!

2021-09-27 11:22 UTC, Dimundra commented on server/const.js
> +const secret = 'owieuricmudfh';
Done!

2021-09-27 11:28 UTC, Dimundra commented on server/controllers/controller.js
> +const authenticateUser = require('../services/auth.js');
Done!

2021-09-27 12:17 UTC, Dimundra commented on server/server.js
> +  server.route([loginRoute]);
Done!

2021-09-27 12:22 UTC, Dimundra commented on server/services/tokenValidation.js
> +      isValid = true;
Done!

2021-09-28 08:48 UTC, kibernetika requested changes

2021-09-28 08:48 UTC, kibernetika commented on client/src/app/pages/SignInPage/SignInPage.js
> +  constructor(props) {
add const STATE_TYPES = { EMAIL: "EMAIL", .... }

2021-09-28 08:48 UTC, kibernetika commented on client/src/app/pages/SignInPage/SignInPage.js
> +                  onChange={(e) => this.handleFormChange(e, 'email')}
then here will be a `  onChange={(e) => this.handleFormChange(e, STATE_TYPES.EMAIL )}`

2021-09-28 08:48 UTC, kibernetika commented on client/src/app/store/actionTypes.js
> +  SET_VALIDATION_ERROR: 'SET_VALIDATION_ERROR',
replace all of these on SET_ERROR

2021-09-28 08:48 UTC, kibernetika commented on client/src/app/store/reducers/errorReducer.js
> +  isError: false,
add 'error_type'

2021-09-28 08:48 UTC, kibernetika commented on server/routes/routes.js
> +let routes = [userRoutes];
const routes = [userRoutes, anotherRoutes, .....].flat();

2021-09-28 08:48 UTC, kibernetika commented on server/routes/userRoutes.js
> +module.exports = userRoutes;
module.exports = [loginRoute]

2021-09-28 11:46 UTC, Dimundra commented on client/src/app/pages/SignInPage/SignInPage.js
> +  constructor(props) {
Done!

2021-09-28 12:04 UTC, Dimundra commented on client/src/app/store/actionTypes.js
> +  SET_VALIDATION_ERROR: 'SET_VALIDATION_ERROR',
Done!

2021-09-28 12:12 UTC, Dimundra commented on client/src/app/store/reducers/errorReducer.js
> +  isError: false,
My suggestion is to not add it for now, as the application at this state doesn't require to identify explicitly error types.

2021-09-28 12:14 UTC, Dimundra commented on server/routes/userRoutes.js
> +module.exports = userRoutes;
Done!

2021-10-04 08:24 UTC, merged